# Add comment related to interrupts action on new issues.
issueOpened: >
  Thank your for opening an issue. Our team's interrupts engineer will reivew your issue shortly.
  
   **Issue Resolution:**
   - [ ] _[Interrupts Engineer]_ Apply triage / categorization labels
   - [ ] _[Interrupts Engineer]_ Verify / Reproduce the reported issue
   - [ ] _[Forseti Engineer]_ Perform root cause analysis
   - [ ] _Forseti Engineer]_ Add tasks and next steps to resolve this issue.

#pullRequestOpened: >
#  Thank your for raising your pull request.
