global:

    # Remove or comment out the email properties if you do not want Forseti to
    # send email notifications.
    email_recipient: "oscarsandoval@google.com"
    sendgrid_api_key: SENDGRID_API_KEY

##############################################################################

inventory:

    # Root resource to start crawling from, formatted as
    # <resource_type>/<resource_id>, (e.g. "organizations/12345677890")
    root_resource_id: organizations/660570133860

    # gsuite
    domain_super_admin_email: oscarsandoval@henrychang.mygbiz.com 

    api_quota:
        # We are not using the max allowed API quota because we wanted to
        # include some rooms for retries.
        # Period is in seconds.

        # Set disable_polling to True to disable polling that API for creation
        # of the inventory. This can speed up inventory creation for
        # organizations that do not use specific APIs. Defaults to False if
        # # not defined.
        admin:
          max_calls: 14
          period: 1.0
          disable_polling: False
        appengine:
          max_calls: 18
          period: 1.0
          disable_polling: True
        bigquery:
          max_calls: 160
          period: 1.0
          disable_polling: True
        cloudasset:
          max_calls: 1
          period: 1.0
          disable_polling: True
        cloudbilling:
          max_calls: 5
          period: 1.2
          disable_polling: True
        compute:
          max_calls: 18
          period: 1.0
          disable_polling: True
        container:
          max_calls: 9
          period: 1.0
          disable_polling: True
        crm:
          max_calls: 4
          period: 1.2
          disable_polling: False
        groupssettings:
          max_calls: 14
          period: 1.0
          disable_polling: False
        iam:
          max_calls: 90
          period: 1.0
          disable_polling: True
        logging:
          max_calls: 9
          period: 1.0
          disable_polling: True
        securitycenter:
          max_calls: 1
          period: 1.1
          disable_polling: True
        servicemanagement:
          max_calls: 2
          period: 1.1
          disable_polling: True
        sqladmin:
          max_calls: 1
          period: 1.1
          disable_polling: True
        storage:  # Does not use API quota
          disable_polling: True

    cai:
        # The FORSETI_CAI_BUCKET needs to be in Forseti project.
        enabled: False
        gcs_path: gs://osandoval-first-bucket


    # Number of days to retain inventory data:
    #  -1 : (default) keep all previous data forever
    #   0 : delete all previous inventory data before running
    retention_days: -1

##############################################################################

scanner:

    # Output path (do not include filename).
    # If GCS location, the format of the path should be:
    # gs://bucket-name/path/for/output
    output_path: gs://osandoval-first-bucket/scanner_violations

    # Rules path (do not include filename).
    # If GCS location, the format of the path should be:
    # gs://bucket-name/path/for/rules_path
    # if no rules_path is specified, rules are
    # searched in /path/to/forseti_security/rules/
    rules_path: /Users/oscarsandoval/devtest/forseti-security/rules

    # Enable the scanners as default to true when integrated for Forseti 2.0.

    scanners:
        - name: audit_logging
          enabled: false
        - name: bigquery
          enabled: false
        - name: blacklist
          enabled: false
        - name: bucket_acl
          enabled: true
        - name: cloudsql_acl
          enabled: false
        - name: enabled_apis
          enabled: false
        - name: firewall_rule
          enabled: false
        - name: forwarding_rule
          enabled: false
        - name: group
          enabled: false
        - name: iam_policy
          enabled: false
        - name: iap
          enabled: false
        - name: instance_network_interface
          enabled: false
        - name: ke_version_scanner
          enabled: false
        - name: lien
          enabled: false
        - name: log_sink
          enabled: false
        - name: service_account_key
          enabled: false

##############################################################################

notifier:

    # For every resource type you can set up a notification pipeline
    # to send alerts for every violation found
    resources:
        - resource: iam_policy_violations
          should_notify: true
          notifiers:
            # Email violations
            - name: email_violations
              configuration:
                data_format: csv
                sendgrid_api_key: ''
                sender: 'oscarsandoval@google.com'
                # Multiple recipients can be specified as comma-separated text.
                recipient: 'oscarsandoval@henrychang.mygbiz.com'
            # Upload violations to GCS.
            - name: gcs_violations
              configuration:
                data_format: csv
                # gcs_path should begin with "gs://"
                gcs_path: gs://osandoval-first-bucket/scanner_violations
            # Slack webhook pipeline
            # Create an incoming webhook in your organization's Slack setting, located at:
            # https://[your_org].slack.com/apps/manage/custom-integrations
            # Add the provided URL in the configuration below in `webhook_url`.
            - name: slack_webhook
              configuration:
                data_format: json  # slack only supports json
                webhook_url: ''

    violation:
      cscc:
        enabled: false
        mode: api
        # Alpha API
        organization_id: organizations/660570133860
        # gcs_path should begin with "gs://"
        gcs_path:
        # Beta API
        # Cloud SCC Beta API uses a new source_id.  It is unique per
        # organization and must be generated via a self-registration process.
        # If source_id is used, then it will activate the Beta API,
        # and the Beta API will take precedence over the Alpha API.
        # The format is: organizations/ORG_ID/sources/SOURCE_ID
        source_id:

    inventory:
      gcs_summary:
        enabled: true
        # data_format may be one of: csv (the default) or json
        data_format: csv
        # gcs_path should begin with "gs://"
        gcs_path: gs://osandoval-first-bucket/inventory_summary
      email_summary:
        enabled: true
        sendgrid_api_key: SENDGRID_API_KEY
        sender: 'oscarsandoval@google.com'
        recipient: 'oscarsandoval@henrychang.mygbiz.com'
